---
- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present
    update_cache: yes
  become: yes

- name: Add dnsmasq configuration file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/dnsmasq.conf.j2"
    dest: /etc/dnsmasq.conf
  become: yes

- name: Enable and restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
    enabled: yes
  become: yes
...
